[build]
  # No build process needed for static files
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000"
    # Security headers
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Special caching for HTML files (shorter cache)
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirects (in case someone tries to access without .html)
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Error page redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
